ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'APPLIED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'REVIEWING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SHORTLISTED';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'INTERVIEWING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'OFFERED';
